### ISSUE TITLE
Fix CodeClimate issues

### ISSUE THREAD

**Issue by ribeirojose** [neo-empresarial/clockify-integration#23]
I took the liberty of attaching an automated code review tool (CodeClimate) to our repository. It detected some code that could be better, so I put this issue here so that anyone can help us fix them. 

Link to the issues [here](https://codeclimate.com/github/neo-empresarial/clockify-integration/issues)

**Comment by lukasab** [comment]
Can you add a description?

**Comment by ribeirojose** [comment]
Can you please comment in which PR this was resolved? @lukasab
