### ISSUE TITLE
Change models string to be lower case

### ISSUE THREAD

**Issue by lukasab** [neo-empresarial/clockify-integration#31]
While @yvesfracari was doing his script we found some inconsistency with strings. Some of the activity names or project names were with some letters in upper case while others were in lower case, this really difficulted his work and could in the future be a problem. I suggest creating a standard by putting all non-important strings from models as lower case (project name, activity name, acronym, email, client name) and letting clockify_id the way it is (with upper and lower case).

**Comment by lukasab** [comment]
@ribeirojose do you see any problems by doing this? We would need to make sure everything is in lower case before consulting the database but I don't think this is a drawback and you? There was this other option to use [citext](https://www.postgresql.org/docs/9.3/citext.html) but I'm not sure how it would work with orator.

**Comment by ribeirojose** [comment]
Is this solved yet?

**Comment by lukasab** [comment]
Yes, it is. Fix in #32 and @yvesfracari found a bug and fixed in #35
