### ISSUE TITLE
Analyze how many hours are logged out of working time

### ISSUE THREAD

**Issue by ribeirojose** [neo-empresarial/clockify-integration#45]
I'm not even sure if this is possible, or how accurate it would be, but it is definitely something I think would generate outputs to our members. Whoever gets this should first analyze its viability first, then do it if it's possible or output to us if it's not and why.

**Comment by ribeirojose** [comment]
This is something I think you'd enjoy @jluizduda

**Comment by mendesfabio** [comment]
Not sure how we would do this, closing this issue for now.
