### ISSUE TITLE
Send email for wrong tags

### ISSUE THREAD

**Issue by yvesfracari** [neo-empresarial/clockify-integration#46]
When a time entry has a wrong client tag the program fixes before sending it to the database and then updates the data on our clockify workspace, but the user didn't know he put something wrong.
The line and file that has to be changed is [this one](https://github.com/neo-empresarial/clockify-integration/blob/4c39b1dd8947605722c197ca724806acb556cb26/models/time_entry.py#L83)

**Comment by lukasab** [comment]
As we are not using tags anymore I will close this issue
