### ISSUE TITLE
Paralelism in time entry insert

### ISSUE THREAD

**Issue by pkretzschmar** [neo-empresarial/clockify-integration#57]
When we populate the database we could make the process use parallelal programming to make it faster.

**Comment by ribeirojose** [comment]
I took the liberty of changing `feature`  for `enhancement` here, as this does not add any new feature to our project.

**Comment by mendesfabio** [comment]
> Due to the Lambda execution environment not having /dev/shm (shared memory for processes) support, you can’t use multiprocessing.Queue or multiprocessing.Pool.

https://aws.amazon.com/pt/blogs/compute/parallel-processing-in-python-with-aws-lambda/

And maybe #70 will fix this already. Closing the issue for now.
