### ISSUE TITLE
Migrate Metabase app database to RDS

### ISSUE THREAD

**Issue by ribeirojose** [neo-empresarial/clockify-integration#61]
There's some things about that [here](https://www.metabase.com/docs/latest/operations-guide/configuring-application-database). Could you help me with it, @lukasab?

**Comment by lukasab** [comment]
Sure! Which database instance type you created on RDS (MySQL, Postgres)? Have you already shared with me the aws account?

**Comment by mendesfabio** [comment]
@lukasab migrated Metabase to new droplet. We still need to buy the domain and set DNS.
