### ISSUE TITLE
Timezone mismatch with time entries

### ISSUE THREAD

**Issue by lukasab** [neo-empresarial/clockify-integration#76]
**Describe the bug**
Our time entries data are stored in UTC timezone but our data types are without timezone. So when calculating PREP the value maybe be different than expected if someone works Sunday night because the time entry may appear on Monday.  

**To Reproduce**
1. Insert a time entry in Clockify on Sunday night
2. Run populate script
3. See time entry in DB on Monday morning

**Expected behavior**
There is no problem saving the time in UTC, actually, it is even better but we should have timezone so if someone does a query in Brazil they get the time of that time entry in the Brazil timezone.

**Additional context**
Orator doesn't support ([yet](https://github.com/sdispater/orator/pull/194)) timezone in timestamps.

I see some solutions to this problem:

1. Save everything in Brazil timezone by changing the python script;
2. Manually change the DB types to timezone aware and let the code as it is;
3. Make a SQL trigger when inserting into time_entry table to change to Brazil timezone.

**Comment by ribeirojose** [comment]
I vote for 2. We shouldn’t let the limitations on the migration solution go in the way of using Postgres types. Sure there isn’t a workaround for this?

**Comment by lukasab** [comment]
I think I can run raw DB queries with Orator, so I guess I can alter the timestamps type with the migrations.
 
But, I found an issue with solution number 2. After changing "start" and "end" columns from time_entry table to time zone aware I still need to find a way using Orator to grab all time entries from a week from a user **using the Brazil time zone** so it can calculate the right PREP value.

If I were using normal SQL queries I would just change my time zone session to Brazil timezone and select * time entries. I need to check how to do this using Orator, maybe I can run a raw DB query to change the time zone before getting all the time entries necessary to calculate the PREP value.
